name: Run OWASP DC scan

#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    types: [opened, synchronize, reopened]
#  schedule:
#    - cron: '41 5 * * 6'

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run dependency-check scan
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'petclinic'
          path: '.'
          format: 'SARIF'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --enableExperimental
            --enableRetired
          
#      - name: Upload Test results
#        uses: actions/upload-artifact@master
#        with:
#           name: Depcheck report
#           path: ${{github.workspace}}/reports

      - name: Inspect action SARIF report
        run: ls -la ${{github.workspace}}/reports
