name: Generate SBOM

on:
  workflow_dispatch: 

jobs:
  sbom:
    name: sbom/report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Gererate XML SBOM
        uses: anchore/sbom-action@v0
        with:
          from: cyclonedx
          output-file: "sbom_cyclonedx.xml"

      - name: Gererate JSON SBOM
        uses: anchore/sbom-action@v0
        with:
          from: cyclonedx-json
          output-file: "sbom_cyclonedx.json"


      - name: Upload reports
        uses: actions/upload-artifact@master
        with:
           name: ${{ github.event.repository.name }} SBOM report
           path: ${{ github.workspace }}/sbom_cyclonedx.*
