name: Run Grype scan

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '48 5 * * 6'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Grype scan
        id: scan
        uses: anchore/scan-action@v3
        with:
          path: "."
          fail-build: false
          output-format: "json"
                
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Grype report
           path: ${{steps.scan.outputs.json}}
