name: Trivy scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: master
  workflow_dispatch: 
  schedule:
    - cron: "0 20 * * 2"

jobs:
  trivy:
    name: trivy/depcheck
    runs-on: ubuntu-latest
    container:
      image: aquasec/trivy
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy fullscan
        run: trivy fs --pkg-types library --scanners vuln --ignore-unfixed --format sarif -o trivy_scan.sarif --severity MEDIUM,HIGH,CRITICAL .
      
      - name: Upload reports
        uses: actions/upload-artifact@master
        with:
           name: trivy-sarif
           path: trivy_scan.sarif

  sonar-import:
    name: Import to SonarQube
    runs-on: ubuntu-latest
    needs: trivy
    steps:
      - uses: actions/checkout@v4

      - name: Download SARIF artifact
        uses: actions/download-artifact@v4
        with:
          name: trivy-sarif

      - name: Import SARIF to SonarQube
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.sarifReportPaths=trivy_scan.sarif
            -Dsonar.sources=.
